name: Publish Ui.Wpf.KanbanControl
on:
  push:
    tags:
      - 'Ui.Wpf.KanbanControl/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:24})
    - uses: actions/checkout@master
      shell: pwsh
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - run: dotnet pack ./Ui.Wpf.KanbanControl/Ui.Wpf.KanbanControl.csproj -c Release -o NuGetPackages /p:Version=$RELEASE_VERSION
    - name: Push to feeds
      env:
        MYGET_SOURCE: https://www.myget.org/F/gabbacode/api/v3/index.json
      run: |
        dotnet nuget push ./NuGetPackages/Monik.Client.Azure.$RELEASE_VERSION.nupkg -k ${{ secrets.MYGET_APIKEY }} -s $MYGET_SOURCE
